---
apiVersion: v1
kind: Secret
metadata:
  name: dockerp-hub-credentials
type: Opaque
data:
  DOCKER_USERNAME: "c2VuZGVy"
  DOCKER_PASSWORD: "FyaVl5STdYMlMzbEE1ODBwK0FTYkhpRlVrQT0="

---
apiVersion: v1
kind: Secret
metadata:
  name: Azure-credentials
type: Opaque
data:
  ZURE_CLIENT_ID: "bGlzdGVuZXI="
  OZURE_CLIENT_SECRET: "NXJsbU15cFk0RzFyUWprUks5K0FTYkF1VzAzOD0="
  AZURE_TENANT_ID: "dYMlMzbEE1ODBwK0FTYkhpRlVrQT0="
